### ISSUE TITLE
Allow searching for "Null" in the filter options

### ISSUE THREAD

**Issue by Rerosempire** [TK3600/moddingSuite#2]
Currently any items that are listed as "Null" are not filterable.
For example here, every BLUFOR unit has a Nationalite of Null.
It would be great if that was an option to put as a filter. 
![image](https://github.com/TK3600/moddingSuite/assets/102901108/63eb80d4-389e-4971-a6da-1b564233905d)

**Comment by TK3600** [comment]
Newest version should have null searchable. Not released yet.

**Comment by Rerosempire** [comment]
Fixed as of 0.9.2
