### ISSUE TITLE
Fix copying of Maplist (high priority)

### ISSUE THREAD

**Issue by Rerosempire** [TK3600/moddingSuite#6]
A map is a collection of 2 items, for example a UInt32 and an Int32.
Here is a screenshot of one (in this case Int32 and List)
![image](https://github.com/TK3600/moddingSuite/assets/102901108/17854661-8eff-4c31-8b4c-a2387db7aaac)

A list of maps in the modding suite is a MapList as you can see here, the type is MapList
![image](https://github.com/TK3600/moddingSuite/assets/102901108/2b2d7c11-b603-44ac-888e-4f04d1e07713)

This is different from a normal List which only contains singular items.
![image](https://github.com/TK3600/moddingSuite/assets/102901108/cb7a7b6d-b65f-49eb-b057-23f1c6fc118d)
(in this case loose Int32s)

When you copy an instance with a Maplist in it the modding suite makes it a normal List which crashes the game or invalidates the values making them do nothing.

Please fix it so that the modding suite makes it a MapList.

**Comment by TK3600** [comment]
https://github.com/TK3600/moddingSuite/blob/master/moddingSuite/Model/Ndfbin/Types/AllTypes/NdfMapList.cs

I believe this is the file. It has some commented out values.

**Comment by Rerosempire** [comment]
Yes, however the error in the moddingsuite is in the copy function itself.
It doesn't have a case for maplist. I tried making one once but its very
hard and needs a good c#-er to do it.

**Comment by Rerosempire** [comment]
Solved as of 0.9.2
